export const USER_A_RESPONSES = "USER_A_RESPONSES";
export const USER_B_RESPONSES = "USER_B_RESPONSES";
export const USER_C_RESPONSES = "USER_C_RESPONSES";
export const USER_D_RESPONSES = "USER_D_RESPONSES";